### ISSUE TITLE
image upload mechanism

### ISSUE THREAD

**Issue by ankurpapneja** [UCLALibrary/CC-ing#6]

**Comment by ankurpapneja** [comment]
The beginning portion of the workflow requires image upload to the server. We need to create an interface that allows individuals to do just that. Task: design a UI and backend that provides such functionality. Also implement a REST API that supports single and multiple image upload. 

To facilitate the OCR process, we need to specify which languages are associated with each book. So create an option in the web upload form and REST API that allows one to specify the language(s). Use the language codes and their associated languages detailed [here](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files).

A couple of other things:
1) Require password to access the UI and use the API so our folder of images doesn't get corrupted.
2) Store images in /var/www/html/test_images on our Apache web server. I've written a script that will look for images here and pipeline them into the later portions of the workflow.
3) Develop a meaningful naming scheme to standardize the referencing of images and files that contain their metadata.

Since we only have language information as metadata at this point, you can include the languages as part of the name i.e. pic341213-eng+lao.jpg, where "eng" and "lao" are [language codes](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files). 

Feel free to split up the tasks amongst yourselves. Comment below if you have any questions.

**Comment by Darthpwner** [comment]
@ankurpapneja Is there any backend you had in mind to do this? Should we implement it in Rails as well?

**Comment by ankurpapneja** [comment]
@Darthpwner It shouldn't matter as it's going on our Apache web server. @broadwell could you confirm?

**Comment by JeffreyQ** [comment]
Somebody already built out a RESTful image uploader using Django and the Django Rest Framework. I got it up and running on my local machine and it supports single as well as multiple image upload. The photos are currently uploaded to a folder in my project directory named "uploaded_media".

Next objective: building password functionality to access the UI. 

<img width="1064" alt="screen shot 2017-04-12 at 3 41 49 pm" src="https://cloud.githubusercontent.com/assets/10890152/24982558/d061ff20-1f96-11e7-80a5-bfe908a1f856.png">

**Comment by JeffreyQ** [comment]
In regards to step #2 it's quite easy to decide where we want the uploaded files to go to. 

Check out Step 2, Ch. 1, of his tutorial. 
https://github.com/ChristianKreuzberger/django-rest-imageupload-example/blob/b52256373ecd53570a98ea57b43456bbc836d707/tutorial/chapter1/step2.md

At the very bottom of his settings.py script he tells the program where to upload the photos. We can modify the directory accordingly.

**Comment by JeffreyQ** [comment]
Password protection of django image uploader enabled. 

Follow the "Quick Start" instructions listed in the below link to launch the django image uploader:
https://github.com/ChristianKreuzberger/django-rest-imageupload-example

To access go to 127.0.0.1:8000 and after logging in you will be able to upload images that will show up in the "sample_images" directory. We also allow access to the static web pages without a password. However, the images uploaded will not go through.

**Comment by ankurpapneja** [comment]
Naming scheme no longer required. All completed.
