### ISSUE TITLE
store OCR result into Scribe

### ISSUE THREAD

**Issue by ankurpapneja** [UCLALibrary/CC-ing#7]
Look through the Ruby code and the different scripts in the source code to figure out how we can store the OCR result into Scribe. Marshal the result into the appropriate format for Scribe.

**Comment by jiminkk** [comment]
So currently, OCR returns a JSON object as found in fileAPIController.java. Since we don't have an OCR API to call from Scribe yet, I'm thinking of saving OCR data into a file every time it's run - then we can open up this file in Scribe

**Comment by broadwell** [comment]
Just a suggestion, if you get tired of reading Ruby code and/or looking around the database: if you enable the Chrome developer console (View->Developer Tools) while marking and transcribing in Scribe, the "Network" activity panel shows that the interface operates by submitting form data to the Scribe server every time the user makes a change, like marking an image title. Specifically, it sends an HTTP POST message to http://<server>:8000/classifications with form data giving the dimensions of the marked area and other metadata (see the example below). It probably wouldn't be easy, but it's possible we could write a script to read the OCR JSON output and then spoof these HTTP messages to get the OCR results into Scribe, using something like Python's [Requests](http://docs.python-requests.org/en/master/) library.

<details>
<summary>Click to see the message payload</summary>
classifications[annotation][belongsToUser]:true
classifications[annotation][toolName]:rectangleTool
classifications[annotation][userCreated]:true
classifications[annotation][subToolIndex]:0
classifications[annotation][color]:red
classifications[annotation][isTranscribable]:true
classifications[annotation][x]:31.855670103092788
classifications[annotation][y]:71.44329896907217
classifications[annotation][width]:28.041237113402065
classifications[annotation][height]:4.2783505154639165
classifications[annotation][_key]:0.2896224356266506
classifications[annotation][status]:mark
classifications[annotation][isUncommitted]:true
classifications[subject_id]:58ed2c5e69702d238a481300
classifications[subject_set_id]:58ed2c5e69702d238a471300
classifications[task_key]:mark_primary
classifications[metadata][started_at]:2017-04-11T21:37:04.843Z
classifications[metadata][finished_at]:2017-04-11T21:37:04.843Z
classifications[workflow_id]:58ed2c3f69702d238a010000
</details>
